### ISSUE TITLE
lock on iOS does not work right after device ready event 

### ISSUE THREAD

**Issue by chiefego** [apache/cordova-plugin-screen-orientation#34] opened 2018-09-05 14:20 UTC
When calling screen.lock immediately after device ready event fires in iOS, the screen is not getting forced. However, it works when calling it after 4000ms.

**Comment by janpio** [comment] 2018-09-05 14:30
What does "is not getting forced" mean?

**Comment by chiefego** [comment] 2018-09-05 14:37
Sorry, what I mean is that when the phone's orientation is `portrait` and you call `screen.lock('landscape')` right after `onDeviceReady` the phone orientation is not changed. If you manually rotate the phone then it locks it. However, when making the same call with a 4s timeout the phone will rotate to landscape automatically.

**Comment by sagrawal31** [comment] 2018-09-06 06:12
This is happening with me randomly as well on iPhoneX and some time in iPhone 6

**Comment by sagrawal31** [comment] 2018-09-06 06:18
I actually see some new commits after the release of 3.0.1 which fixes some landscape orientation issues. Is 3.0.2-dev branch production ready?

**Comment by janpio** [comment] 2018-09-06 08:56
You tell us ;) Usually there should only be working code in `master`.

**Comment by am** [comment] 2018-09-26 21:04
@janpio This is still happening on 3.0.1

**Comment by mpotter-modus** [comment] 2018-11-12 15:08
Confirmed - we're having the same issue. Looks like this was fixed in a89e94c

Any plans to publish an update to the NPM repo @jcesarmobile / @macdonst ?

**Comment by jcesarmobile** [comment] 2018-11-12 15:12
Closing as it's fixed in that commit

**Closed by jcesarmobile** 2018-11-12 15:12 UTC
Labels: platform: ios, support

**Comment by mpotter-modus** [comment] 2018-11-12 17:59
@jcesarmobile could we get a new release please so the changes can be pulled from the NPM repo?

**Comment by jcesarmobile** [comment] 2018-11-12 18:07
I don't know how to do Apache plugin releases, sorry, it's not as simple as publishing it in npm
